In [19]:
from skimage import io

original = io.imread('C:/Users/Usuario-PC/Dropbox/Angeles-Gisela-Andrea/Images/SAR Images/ SanFrancisco.jpg')

In [20]:
original

array([[248, 219, 180, ...,   2,   0,   0],
       [255, 244, 225, ...,   4,   3,   2],
       [238, 225, 248, ...,   4,   4,   3],
       ...,
       [253, 254, 255, ...,  28,  51,  14],
       [251, 253, 255, ...,  59,  42,   0],
       [249, 253, 255, ..., 100,  83,  21]], dtype=uint8)

In [21]:
im = np.matrix(original)

In [22]:
im

matrix([[248, 219, 180, ...,   2,   0,   0],
        [255, 244, 225, ...,   4,   3,   2],
        [238, 225, 248, ...,   4,   4,   3],
        ...,
        [253, 254, 255, ...,  28,  51,  14],
        [251, 253, 255, ...,  59,  42,   0],
        [249, 253, 255, ..., 100,  83,  21]], dtype=uint8)

In [2]:
from skimage import io,util,exposure
import numpy as np
import numpy.ma as ma

def thresholdedImage(img, thr):
    
    """
thresholdedImage function

Arguments:
img a "numpy.ndarray" object
thr a list of thresholds

Value:
thresholdingImage returns an object with class "numpy.ndarray" and possible values 0,1,...,255

"""

    # Normalize gray levels in the range 0,1,...,255
    
    image = util.img_as_ubyte(img)

    #Convert threshold to numpy array

    if(isinstance(thr, int)):
        thr = np.array([thr], dtype=int)

    thr = np.array(thr, dtype=int)

    _, counts = np.unique(thr, return_counts=True) 
    for count in counts:
        if(count == 1):
            continue
        print("[Error!]: there are repetead values in 'thr' (list of thresholds) argument") #Error check
        exit()
    
    # Find and sort gray levels
    
    _, grays = exposure.histogram(img)
    
    # Find amount of gray levels and thresholds

    L = grays.size
    
    K = thr.size
    
    if(K == 0):
        print("[Error!]: 'thr', list of thresholds, is empty") #Error check
        exit()
    if(K>L):
        print("[Error!]: 'thr', list of thresholds, contains more values than the amount of gray levels") #Error check
        exit()

    # Compute the grayscale mean in each class

    avg = np.zeros(1)
    avg[0] = np.mean(grays[0:(thr[0]+1)])
    if(K != 1):
        for i in range(1, K):
            avg = np.append(avg, np.mean(grays[(thr[i-1]+1):(thr[i]+1)]))
    avg = np.append(avg, np.mean(grays[(thr[K-1]+1):]))

    # Round the means

    avg = np.round(avg)

    # Replace each gray value in the image by the mean of its class

    np.place(image, ma.masked_inside(image, grays[0], grays[thr[0]]), avg[0])
    if(K != 1):
        for i in range(1, K):
            np.place(image, ma.masked_inside(image, grays[thr[i-1]+1], grays[thr[i]]), avg[i])
    np.place(image, ma.masked_inside(image, grays[thr[K-1]+1], grays[L-1]), avg[K])


    #Output

    return image

In [15]:
image1 = thresholdedImage(original, 100)

In [4]:
type(image1)

numpy.ndarray

In [16]:
image1

array([[178, 178, 178, ..., 178,   0,   0],
       [178, 178, 178, ..., 178, 178, 178],
       [178, 178, 178, ..., 178, 178, 178],
       ...,
       [178, 178, 178, ..., 178, 178, 178],
       [178, 178, 178, ..., 178, 178,   0],
       [178, 178, 178, ..., 178, 178, 178]], dtype=uint8)

In [23]:
im1 = np.matrix(image1)

In [24]:
im-im1

matrix([[ 70,  41,   2, ...,  80,   0,   0],
        [ 77,  66,  47, ...,  82,  81,  80],
        [ 60,  47,  70, ...,  82,  82,  81],
        ...,
        [ 75,  76,  77, ..., 106, 129,  92],
        [ 73,  75,  77, ..., 137, 120,   0],
        [ 71,  75,  77, ..., 178, 161,  99]], dtype=uint8)

In [3]:
grises = [0,1,2,3,4]
prob = [0.1,0.2,0.3,0.3,0.1]
clust = [0,1,2]

import bibliotecaFunciones as bf

bf.cluster_mean(prob, clust, 0)


1.3333333333333333